In [1]:
# imports

from scipy.io import loadmat
import numpy as np

In [2]:
avi_data_mult = list()
for i in range(1,6):
    for j in range(1,3):
        avi_data_mult.append(loadmat(f"datasets/avi/multi/Sub{i}_{j}_multitarget.mat"))



X = [d['Data'][0][0][7] for d in avi_data_mult]
y = [d['Data'][0][0][8][0] for d in avi_data_mult]

print("Divisão dos dados:")


X = [data.T for data in X]


for data in X:
    print(data.shape)
for data in y:
    
    print(data)

    


Divisão dos dados:
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
