In [9]:
# imports

from scipy.io import loadmat
import numpy as np

In [10]:
# pré-carregamento

avi_data = list()
for i in range(1,6):
    avi_data.append(loadmat(f"../datasets/avi/multi/Sub{i}_1_multitarget.mat"))
    avi_data.append(loadmat(f"../datasets/avi/multi/Sub{i}_2_multitarget.mat"))

In [11]:
# extração direta dos dados

X = [d['Data'][0][0][7] for d in avi_data]
y = [d['Data'][0][0][8][0] for d in avi_data]

print("Divisão dos dados:")
for data in X:
    print(data.shape, data.T.shape)

print("\nDivisão dos rótulos (sequências):")
for data in y:
    print(data)

Divisão dos dados:
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)

Divisão dos rótulos (sequências):
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]


In [12]:
# Mudando o formato de X
X_transposed = np.array([np.transpose(data) for data in X])
X_transposed = X_transposed.reshape(X_transposed.shape[0]*X_transposed.shape[1], X_transposed.shape[2])
X_transposed.shape

y_transposed = np.array([np.transpose(data) for data in y])
y_transposed = y_transposed.reshape(1, y_transposed.shape[0]*y_transposed.shape[1])[0]
y_transposed

array([7.5, 8.2, 7. , 8.2, 6. , 7.5, 6. , 6. , 8.2, 8.2, 9.3, 6. , 6. ,
       8.2, 6. , 6.5, 7.5, 7. , 6. , 6. , 7.5, 8.2, 7. , 8.2, 6. , 7.5,
       6. , 6. , 8.2, 8.2, 9.3, 6. , 6. , 8.2, 6. , 6.5, 7.5, 7. , 6. ,
       6. , 7.5, 8.2, 7. , 8.2, 6. , 7.5, 6. , 6. , 8.2, 8.2, 9.3, 6. ,
       6. , 8.2, 6. , 6.5, 7.5, 7. , 6. , 6. , 7.5, 8.2, 7. , 8.2, 6. ,
       7.5, 6. , 6. , 8.2, 8.2, 9.3, 6. , 6. , 8.2, 6. , 6.5, 7.5, 7. ,
       6. , 6. , 7.5, 8.2, 7. , 8.2, 6. , 7.5, 6. , 6. , 8.2, 8.2, 9.3,
       6. , 6. , 8.2, 6. , 6.5, 7.5, 7. , 6. , 6. ])

In [13]:
np.save("../datasets/avi/multi/dataMulti_sub1.npy", X_transposed)
np.save("../datasets/avi/multi/labelsMulti_sub1.npy", y_transposed)


# for i in range(0,10):
#     np.save(f"../datasets/avi/multi/datMulti_sub{i}.npy", X[i])
#     np.save(f"../datasets/avi/multi/labelMulti_sub{i}.npy", y[i])